# Generated by Django 4.2.2 on 2023-07-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prescription_picture_url', models.URLField()),
                ('phone_number', models.CharField(max_length=15)),
                ('area', models.CharField(choices=[('Bashundhara', 'Bashundhara'), ('Bailey Road', 'Bailey Road')], max_length=60)),
                ('address', models.TextField()),
                ('delivery_status', models.CharField(choices=[('pending', 'pending'), ('prescription_received', 'Prescription Received'), ('dispatched', 'Dispatched'), ('complete', 'Complete')], default='pending', max_length=40)),
                ('notes', models.TextField(blank=True, null=True)),
                ('deliveryman_name', models.CharField(blank=True, max_length=100, null=True)),
                ('deliveryman_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_recurrence', models.CharField(choices=[('one_time', 'One Time'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='one_time', max_length=10)),
                ('intervals_recurring', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
