# Generated by Django 4.2.2 on 2023-07-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorder',
            name='uid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicineorder',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'pending'), ('prescription_received', 'Prescription Received'), ('dispatched', 'Dispatched'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='pending', max_length=40),
        ),
    ]
