# Generated by Django 4.2.2 on 2023-07-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_orders', '0002_medicineorder_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineorder',
            name='uid',
            field=models.CharField(default=12345678, max_length=200),
            preserve_default=False,
        ),
    ]
